version: "3"

services:
  tomcat:
    build:
      context: ./
      dockerfile: ./.docker/tomcat/Dockerfile
    volumes:
    - "./.docker/tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml"
    - "./.docker/tomcat/context.xml:/usr/local/tomcat/webapps/manager/META-INF/context.xml"
    - "./target/myapp.war:/usr/local/tomcat/webapps/myapp.war"
    ports:
      - '8082:8080'